import { existsSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { changedFiles, codeTree, diffBase, gatesDir, readJson, readRun, repoRoot } from './gates-lib.mjs';
import { homedir } from 'node:os';
import { GATES, requiredGates, reviewDrift, staleReason } from './gates-registry.mjs';

const PR_BODY_LIMIT = 1500;
const NATIVE_RE = /^mobile\//;
const CONTRACT_RE = /^shared\/|routes?\/|\.schema\.ts$/;

const featureIndex = process.argv.indexOf('--feature');
const featureDir = featureIndex === -1 ? null : process.argv[featureIndex + 1];
const mode = process.argv[2];
if (!featureDir) { console.error('usage: render.mjs status|pr-body|handover --feature <dir>'); process.exit(1); }

const root = repoRoot();
const run = readRun(featureDir);
if (!run) { console.error(`render: ${featureDir} has no .gates/run.json — run gate-run init first`); process.exit(1); }
const tree = codeTree();
const changed = changedFiles(diffBase(run));
const required = requiredGates(changed, { track: run.track });

const handoff = readJson(join(gatesDir(featureDir), 'handoff.json'));
const receipts = required.map((name) => ({ name, receipt: readJson(join(gatesDir(featureDir), `${name}.json`)) }));
const waivers = receipts.filter((r) => r.receipt?.status === 'waived');
const gateLine = receipts
  .map(({ name, receipt }) => {
    if (!receipt) return `${name} ✗`;
    if (receipt.status === 'waived') return `${name} ⚠`;
    if (receipt.status !== 'pass' || staleReason(featureDir, name, receipt, tree)) return `${name} ✗`;
    const advisory = GATES[name]?.advisory ? ' (advisory)' : '';
    const drift = GATES[name]?.anchor === 'review' ? reviewDrift(receipt, run) : null;
    if (!drift) return `${name} ✓${advisory}`;
    return `${name} ${drift.state === 'unseen' ? '✗' : '✓⚠'}${advisory}`;
  })
  .join(' · ');

function driftNote(drift) {
  if (!drift) return '';
  if (drift.state === 'untracked') return ' — **дрейф не отслеживается** (рецепт без `headSha`)';
  if (drift.state === 'unresolvable') return ` — **анкер \`${drift.sha}\` недостижим** (rebase/amend/squash)`;
  if (drift.state === 'unseen') return ` — **ревью не видело ${drift.unseen.length} файл(ов)**, анкер \`${drift.sha}\``;
  return ` — отревьюено на \`${drift.sha}\`, после него изменено ${drift.files.length} файл(ов)`;
}

const forPublicBody = (path) => {
  if (path.startsWith(`${root}/`)) return path.slice(root.length + 1);
  return path.startsWith(homedir()) ? path.replace(homedir(), '~') : path;
};

function isDirectory(path) {
  try {
    return statSync(path).isDirectory();
  } catch {
    return !/\.[A-Za-z0-9]{1,5}$/.test(path);
  }
}

function evidenceFolders() {
  const seen = new Map();
  for (const { name, receipt } of receipts) {
    const paths = [receipt?.evidencePath, ...(receipt?.artifacts ?? []).map((a) => a.path)]
      .filter((rel) => rel && rel.includes('/'));
    for (const rel of paths) {
      const abs = rel.startsWith('/') ? rel : join(root, rel);
      const folder = isDirectory(abs) ? abs : dirname(abs);
      if (!seen.has(folder)) seen.set(folder, name);
    }
  }
  return [...seen].map(([folder, gate]) => ({ folder, gate }));
}

const REQUIREMENT_RE = /^\s*[-*#]*\s*\*{0,2}R[0-9]+\b/;

function gatherRequirements(spec) {
  const found = [];
  let open = null;
  for (const line of spec.split('\n')) {
    if (REQUIREMENT_RE.test(line)) {
      if (open) found.push(open);
      open = line.trim().replace(/^[-*#]+\s+/, '');
      continue;
    }
    if (!open) continue;
    if (!line.trim() || /^\s*[-*#]/.test(line)) {
      found.push(open);
      open = null;
      continue;
    }
    open += ` ${line.trim()}`;
  }
  if (open) found.push(open);
  return found;
}

if (mode === 'handover') {
  const folders = evidenceFolders();
  const specPathForRn = join(root, featureDir, 'spec.md');
  const requirements = existsSync(specPathForRn) ? gatherRequirements(readFileSync(specPathForRn, 'utf8')) : [];
  const lines = ['## Проверить руками', ''];
  if (folders.length) {
    lines.push('Скриншоты и артефакты:', '');
    for (const { folder, gate } of folders) {
      lines.push(`- ${gate}: \`${folder}\`${existsSync(folder) ? '' : ' (папки уже нет на диске)'}`);
    }
    lines.push('', `Открыть: \`open ${folders.map((f) => `'${f.folder}'`).join(' ')}\``, '');
  } else {
    lines.push('Артефактов на диске нет — ни один гейт не записал evidence.', '');
  }
  if (requirements.length) {
    lines.push('Что проверить по требованиям из spec.md:', '', ...requirements.map((r) => `- [ ] ${r}`), '');
  }
  lines.push('Шаги воспроизведения пиши здесь сам — экран, путь до него, что нажать, что должно произойти.');
  console.log(lines.join('\n'));
  process.exit(0);
}

if (mode === 'status') {
  const lines = [
    '<!-- generated by render.mjs — never hand-edit; run `node render.mjs status` -->',
    `# ${featureDir}`,
    '',
    `- branch: \`${run.branch}\``,
    `- mode: ${run.mode}`,
    `- track: ${run.track ?? 'full'}`,
    `- codeTree: \`${tree.slice(0, 12)}\``,
    `- kill-review due: ${run.killReviewDue}`,
    handoff && handoff.mode === 'handoff'
      ? `- carrier session: \`${handoff.sessionId}\` → \`claude --resume ${handoff.sessionId}\``
      : handoff ? '- handoff: prompt recorded, no carrier spawned (attended) — SessionStart re-injects it after /clear' : null,
    '',
    '| gate | status | artifacts |',
    '|---|---|---|',
    ...receipts.map(({ name, receipt }) => {
      if (!receipt) return `| ${name} | **NOT RUN** | — |`;
      const art = receipt.artifacts?.length ? `${receipt.artifacts.length} file(s)` : '—';
      if (receipt.status === 'waived') return `| ${name} | waived: ${receipt.reason} | ${art} |`;
      const stale = receipt.status === 'pass' && staleReason(featureDir, name, receipt, tree);
      if (stale) return `| ${name} | **STALE** — ${stale} | ${art} |`;
      const drift = receipt.status === 'pass' && GATES[name]?.anchor === 'review' ? reviewDrift(receipt, run) : null;
      const status = drift?.state === 'unseen'
        ? '**блокирует**'
        : `${receipt.status}${GATES[name]?.advisory ? ' (advisory)' : ''}`;
      return `| ${name} | ${status}${driftNote(drift)} | ${art} |`;
    }),
  ].filter((l) => l !== null);
  writeFileSync(join(root, featureDir, 'status.md'), `${lines.join('\n')}\n`);
  console.log('status.md rendered');
  process.exit(0);
}

const specPath = join(root, featureDir, 'spec.md');
const why = existsSync(specPath)
  ? (readFileSync(specPath, 'utf8').split('\n').find((l) => l.trim() && !l.startsWith('#') && !l.startsWith('Source')) ?? '').trim()
  : '';

const outstanding = (() => {
  const path = join(root, featureDir, 'review.md');
  if (!existsSync(path)) return [];
  return readFileSync(path, 'utf8').split('\n').filter((l) => /^\s*[-*]\s*\[( |x)?\]?\s*(MAJOR|CRITICAL|OUTSTANDING)/i.test(l)).slice(0, 5);
})();

const BANNER_REASON_LIMIT = 160;
const short = (text) => (String(text).length > BANNER_REASON_LIMIT
  ? `${String(text).slice(0, BANNER_REASON_LIMIT)}… (полностью — в status.md)`
  : String(text));

const head = [];
if (run.track === 'lite') {
  head.push('> ⚠️ **Трек `lite`** — гейт `plan-approved` не требовался: прогон стартовал на `lite`. Это решение на старте, а не пропуск.', '');
}
if (waivers.length) {
  const shown = waivers.slice(0, 2).map((w) => `\`${w.name}\` — ${short(w.receipt.reason)}`).join('; ');
  const rest = waivers.length > 2 ? ` (+${waivers.length - 2} ещё — см. status.md)` : '';
  head.push(`> ⚠️ **Waived:** ${shown}${rest}`, '');
}
const parts = [];
const releaseNote = (() => {
  if (changed.some((f) => NATIVE_RE.test(f))) {
    return '> ⚠️ **Порядок релиза** — сначала веб-клиент, потом нативный бинарь: бинарь из стора откатить нельзя, а старый веб не поймёт новых нативных кодов.';
  }
  if (changed.some((f) => CONTRACT_RE.test(f))) {
    return '> ⚠️ **Порядок релиза** — сначала СЕРВЕР, потом клиент: контракт изменён, и развёрнутый клиент читает старый ответ.';
  }
  return null;
})();
if (releaseNote) head.push(releaseNote, '');
const PINNED = `**Гейты @ \`${tree.slice(0, 8)}\`:** ${gateLine || 'не требуются'}\nБандл: \`${featureDir}\``;
if (outstanding.length) parts.push('**Outstanding:**', ...outstanding, '');
parts.push(`**Why:** ${why || 'see spec.md'}`, '');

const reviewRows = receipts
  .filter(({ name }) => name.startsWith('review-'))
  .map(({ name, receipt }) => {
    const dimension = name.replace('review-', '');
    if (!receipt) return `| ${dimension} | **не запускалась** |`;
    if (receipt.status === 'waived') return `| ${dimension} | снят: ${receipt.reason} |`;
    if (receipt.status !== 'pass') return `| ${dimension} | ${receipt.status} |`;
    const drift = reviewDrift(receipt, run);
    return `| ${dimension} | прошла${drift ? ` ⚠${driftNote(drift)}` : ''} |`;
  });
if (reviewRows.length) {
  parts.push('**Ревью по измерениям:**', '', '| измерение | статус |', '|---|---|', ...reviewRows, '');
}

const evidence = receipts
  .filter(({ receipt }) => receipt?.artifacts?.length)
  .map(({ name, receipt }) => `${name} (${receipt.artifacts.length} файл(ов))`);

if (evidence.length) parts.push(`**Доказательства:** ${evidence.join(' · ')}`);
const shotFolders = evidenceFolders();
if (shotFolders.length) parts.push(`**Скриншоты:** \`${shotFolders.map((f) => forPublicBody(f.folder)).join('` · `')}\``);
const tail = parts;

const NOTICE = `_Truncated — see \`${featureDir}/status.md\` and \`${featureDir}/review.md\`._`;
const FLOOR = PINNED.length + NOTICE.length + 4;
let body = [...head, PINNED, '', ...tail].join('\n');
if (body.length > PR_BODY_LIMIT - 1) {
  const room = PR_BODY_LIMIT - 1 - FLOOR;
  let kept = '';
  for (const ch of [...head, ...tail].join('\n')) {
    if (kept.length + ch.length > Math.max(0, room)) break;
    kept += ch;
  }
  body = `${kept}\n\n${PINNED}\n\n${NOTICE}`.slice(0, PR_BODY_LIMIT - 1);
}
writeFileSync(join(root, featureDir, 'pr-body.md'), `${body}\n`);
const trimmedBy = [...head, PINNED, '', ...tail].join('\n').length - body.length;
console.log(`pr-body.md rendered — ${body.length + 1} chars on disk (limit ${PR_BODY_LIMIT})${trimmedBy > 0 ? `, ${trimmedBy} trimmed` : ''}`);
